name: BuildAndRelease

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow
          git fetch --tags

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true

      - name: Build Release
        run: dotnet build --configuration Release

      - name: Update update.json & commit
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $version = "${{ steps.gitversion.outputs.SemVer }}"
          $path = "ADUserGroupManager/update.json"
          (Get-Content $path) `
            -replace '"version"\s*:\s*".*"', '"version": "' + $version + '"' `
            -replace '"downloadUrl"\s*:\s*".*"', '"downloadUrl": "https://github.com/IItheshadowII/ADUserGroupManager/releases/download/v' + $version + '/ADUserGroupManagerMerged.exe"' |
            Set-Content $path

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $path
          git commit -m "chore: bump update.json to v$version"
          git push

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          releaseName: "Release ${{ steps.gitversion.outputs.SemVer }}"
          draft: false
          prerelease: false
          artifacts: |
            bin/Release/net48/ADUserGroupManagerMerged.exe
            ADUserGroupManager/update.json
